#!/usr/bin/env bash

protoc \
  -I . \
  -I ../../../include/ \
  --go_opt=paths=source_relative \
  --go_out=paths=source_relative:. \
  --go-grpc_out=paths=source_relative:. \
  *.proto

if [ $? -ne 0 ]; then
    echo FAIL
    exit 1
fi
