#!/usr/bin/env bash

PTYPES=`go list -f '{{ .Dir }}' -m github.com/golang/protobuf`

protoc \
     -I . \
     -I ${PTYPES}/ptypes \
     --go_out=paths=source_relative:. \
     --go-grpc_out=paths=source_relative:. *.proto

if [ $? -ne 0 ]; then
    echo FAIL
    exit 1
fi
