// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package zeropsVpnProtocol

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_NO_ERROR               ErrorCode = 0
	ErrorCode_INTERNAL_SERVER_ERROR  ErrorCode = 1
	ErrorCode_INSTANCE_NOT_FOUND     ErrorCode = 2
	ErrorCode_PROXY_IS_FULL          ErrorCode = 3
	ErrorCode_INVALID_SIGNATURE      ErrorCode = 4
	ErrorCode_EXPIRED_SIGNATURE      ErrorCode = 5
	ErrorCode_MAX_PARALLEL_VPN_LIMIT ErrorCode = 6
)

var ErrorCode_name = map[int32]string{
	0: "NO_ERROR",
	1: "INTERNAL_SERVER_ERROR",
	2: "INSTANCE_NOT_FOUND",
	3: "PROXY_IS_FULL",
	4: "INVALID_SIGNATURE",
	5: "EXPIRED_SIGNATURE",
	6: "MAX_PARALLEL_VPN_LIMIT",
}

var ErrorCode_value = map[string]int32{
	"NO_ERROR":               0,
	"INTERNAL_SERVER_ERROR":  1,
	"INSTANCE_NOT_FOUND":     2,
	"PROXY_IS_FULL":          3,
	"INVALID_SIGNATURE":      4,
	"EXPIRED_SIGNATURE":      5,
	"MAX_PARALLEL_VPN_LIMIT": 6,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=zeropsVpnProtocol.ErrorCode" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_NO_ERROR
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type IP struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IP) Reset()         { *m = IP{} }
func (m *IP) String() string { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()    {}
func (*IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IP.Unmarshal(m, b)
}
func (m *IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IP.Marshal(b, m, deterministic)
}
func (m *IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IP.Merge(m, src)
}
func (m *IP) XXX_Size() int {
	return xxx_messageInfo_IP.Size(m)
}
func (m *IP) XXX_DiscardUnknown() {
	xxx_messageInfo_IP.DiscardUnknown(m)
}

var xxx_messageInfo_IP proto.InternalMessageInfo

func (m *IP) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type IPRange struct {
	Ip                   []byte   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask                 []byte   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPRange) Reset()         { *m = IPRange{} }
func (m *IPRange) String() string { return proto.CompactTextString(m) }
func (*IPRange) ProtoMessage()    {}
func (*IPRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *IPRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPRange.Unmarshal(m, b)
}
func (m *IPRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPRange.Marshal(b, m, deterministic)
}
func (m *IPRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPRange.Merge(m, src)
}
func (m *IPRange) XXX_Size() int {
	return xxx_messageInfo_IPRange.Size(m)
}
func (m *IPRange) XXX_DiscardUnknown() {
	xxx_messageInfo_IPRange.DiscardUnknown(m)
}

var xxx_messageInfo_IPRange proto.InternalMessageInfo

func (m *IPRange) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *IPRange) GetMask() []byte {
	if m != nil {
		return m.Mask
	}
	return nil
}

type Timestamp struct {
	IsSet                bool     `protobuf:"varint,1,opt,name=isSet,proto3" json:"isSet,omitempty"`
	Seconds              int64    `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetIsSet() bool {
	if m != nil {
		return m.IsSet
	}
	return false
}

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type StartVpnRequest struct {
	InstanceId           string     `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	UserId               string     `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientPublicKey      string     `protobuf:"bytes,3,opt,name=clientPublicKey,proto3" json:"clientPublicKey,omitempty"`
	Signature            string     `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Expiry               *Timestamp `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartVpnRequest) Reset()         { *m = StartVpnRequest{} }
func (m *StartVpnRequest) String() string { return proto.CompactTextString(m) }
func (*StartVpnRequest) ProtoMessage()    {}
func (*StartVpnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *StartVpnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVpnRequest.Unmarshal(m, b)
}
func (m *StartVpnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVpnRequest.Marshal(b, m, deterministic)
}
func (m *StartVpnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVpnRequest.Merge(m, src)
}
func (m *StartVpnRequest) XXX_Size() int {
	return xxx_messageInfo_StartVpnRequest.Size(m)
}
func (m *StartVpnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVpnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartVpnRequest proto.InternalMessageInfo

func (m *StartVpnRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *StartVpnRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StartVpnRequest) GetClientPublicKey() string {
	if m != nil {
		return m.ClientPublicKey
	}
	return ""
}

func (m *StartVpnRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *StartVpnRequest) GetExpiry() *Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type StartVpnResponse struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Vpn                  *StartVpnOutDto `protobuf:"bytes,2,opt,name=vpn,proto3" json:"vpn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StartVpnResponse) Reset()         { *m = StartVpnResponse{} }
func (m *StartVpnResponse) String() string { return proto.CompactTextString(m) }
func (*StartVpnResponse) ProtoMessage()    {}
func (*StartVpnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *StartVpnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVpnResponse.Unmarshal(m, b)
}
func (m *StartVpnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVpnResponse.Marshal(b, m, deterministic)
}
func (m *StartVpnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVpnResponse.Merge(m, src)
}
func (m *StartVpnResponse) XXX_Size() int {
	return xxx_messageInfo_StartVpnResponse.Size(m)
}
func (m *StartVpnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVpnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartVpnResponse proto.InternalMessageInfo

func (m *StartVpnResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *StartVpnResponse) GetVpn() *StartVpnOutDto {
	if m != nil {
		return m.Vpn
	}
	return nil
}

type StartVpnOutDto struct {
	Port                 int64    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	ServerPublicKey      string   `protobuf:"bytes,2,opt,name=serverPublicKey,proto3" json:"serverPublicKey,omitempty"`
	AssignedClientIp     *IP      `protobuf:"bytes,3,opt,name=assignedClientIp,proto3" json:"assignedClientIp,omitempty"`
	ServerIp             *IP      `protobuf:"bytes,4,opt,name=serverIp,proto3" json:"serverIp,omitempty"`
	VpnIpRange           *IPRange `protobuf:"bytes,5,opt,name=vpnIpRange,proto3" json:"vpnIpRange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartVpnOutDto) Reset()         { *m = StartVpnOutDto{} }
func (m *StartVpnOutDto) String() string { return proto.CompactTextString(m) }
func (*StartVpnOutDto) ProtoMessage()    {}
func (*StartVpnOutDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *StartVpnOutDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVpnOutDto.Unmarshal(m, b)
}
func (m *StartVpnOutDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVpnOutDto.Marshal(b, m, deterministic)
}
func (m *StartVpnOutDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVpnOutDto.Merge(m, src)
}
func (m *StartVpnOutDto) XXX_Size() int {
	return xxx_messageInfo_StartVpnOutDto.Size(m)
}
func (m *StartVpnOutDto) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVpnOutDto.DiscardUnknown(m)
}

var xxx_messageInfo_StartVpnOutDto proto.InternalMessageInfo

func (m *StartVpnOutDto) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *StartVpnOutDto) GetServerPublicKey() string {
	if m != nil {
		return m.ServerPublicKey
	}
	return ""
}

func (m *StartVpnOutDto) GetAssignedClientIp() *IP {
	if m != nil {
		return m.AssignedClientIp
	}
	return nil
}

func (m *StartVpnOutDto) GetServerIp() *IP {
	if m != nil {
		return m.ServerIp
	}
	return nil
}

func (m *StartVpnOutDto) GetVpnIpRange() *IPRange {
	if m != nil {
		return m.VpnIpRange
	}
	return nil
}

func init() {
	proto.RegisterEnum("zeropsVpnProtocol.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Error)(nil), "zeropsVpnProtocol.error")
	proto.RegisterType((*IP)(nil), "zeropsVpnProtocol.IP")
	proto.RegisterType((*IPRange)(nil), "zeropsVpnProtocol.IPRange")
	proto.RegisterType((*Timestamp)(nil), "zeropsVpnProtocol.Timestamp")
	proto.RegisterType((*StartVpnRequest)(nil), "zeropsVpnProtocol.startVpnRequest")
	proto.RegisterType((*StartVpnResponse)(nil), "zeropsVpnProtocol.startVpnResponse")
	proto.RegisterType((*StartVpnOutDto)(nil), "zeropsVpnProtocol.startVpnOutDto")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xf9, 0x6a, 0x32, 0x29, 0xa9, 0xb3, 0xa2, 0x95, 0xa9, 0xaa, 0x2a, 0x98, 0x4b, 0x84,
	0x44, 0x04, 0x29, 0x27, 0x6e, 0x56, 0xeb, 0xa2, 0x15, 0xae, 0x63, 0xc6, 0x69, 0x54, 0xb8, 0x58,
	0x6e, 0xbc, 0x2a, 0x16, 0xcd, 0x7a, 0xd9, 0x75, 0x0a, 0xe5, 0xc4, 0xdf, 0xe1, 0x97, 0xf0, 0xb7,
	0x90, 0x37, 0x4e, 0x5b, 0xd2, 0xb4, 0xb7, 0x9d, 0x37, 0x6f, 0x66, 0x3c, 0xef, 0xed, 0x1a, 0x3a,
	0x42, 0x66, 0x79, 0x36, 0xcd, 0x2e, 0x07, 0xfa, 0x40, 0xba, 0xbf, 0x98, 0xcc, 0x84, 0x9a, 0x08,
	0x1e, 0x94, 0x09, 0x3b, 0x84, 0x3a, 0x93, 0x32, 0x93, 0xe4, 0x0d, 0xd4, 0xa6, 0x59, 0xc2, 0x2c,
	0xa3, 0x67, 0xf4, 0x3b, 0xc3, 0xbd, 0xc1, 0x3d, 0xea, 0x40, 0xf3, 0x0e, 0xb3, 0x84, 0xa1, 0x66,
	0x12, 0x0b, 0x36, 0x66, 0x4c, 0xa9, 0xf8, 0x82, 0x59, 0x95, 0x9e, 0xd1, 0x6f, 0xe1, 0x32, 0xb4,
	0xf7, 0xa1, 0x42, 0x83, 0x22, 0x1f, 0x27, 0x89, 0x64, 0x4a, 0xe9, 0xa6, 0x9b, 0xb8, 0x0c, 0xed,
	0xd7, 0xb0, 0x41, 0x03, 0x8c, 0xf9, 0x05, 0x23, 0x1d, 0xa8, 0xa4, 0xa2, 0xcc, 0x57, 0x52, 0x41,
	0x08, 0xd4, 0x66, 0xb1, 0xfa, 0xa6, 0x3b, 0x6e, 0xa2, 0x3e, 0xdb, 0x9f, 0xa0, 0x35, 0x4e, 0x67,
	0x4c, 0xe5, 0xf1, 0x4c, 0x90, 0x67, 0x50, 0x4f, 0x55, 0xc8, 0x72, 0x5d, 0xd3, 0xc4, 0x45, 0x50,
	0xcc, 0x52, 0x6c, 0x9a, 0xf1, 0x44, 0xe9, 0xca, 0x2a, 0x2e, 0xc3, 0x82, 0xcf, 0x63, 0x9e, 0x29,
	0xab, 0xda, 0x33, 0xfa, 0x75, 0x5c, 0x04, 0xf6, 0x5f, 0x03, 0xb6, 0x54, 0x1e, 0xcb, 0x7c, 0x22,
	0x38, 0xb2, 0xef, 0x73, 0xa6, 0x72, 0xb2, 0x0f, 0x90, 0x72, 0x95, 0xc7, 0x7c, 0xca, 0x68, 0xa2,
	0xdb, 0xb7, 0xf0, 0x0e, 0x42, 0x76, 0xa0, 0x31, 0x57, 0x4c, 0xd2, 0xa4, 0x5c, 0xb7, 0x8c, 0x48,
	0x1f, 0xb6, 0xa6, 0x97, 0x29, 0xe3, 0x79, 0x30, 0x3f, 0xbf, 0x4c, 0xa7, 0x1f, 0xd9, 0xb5, 0x9e,
	0xd5, 0xc2, 0x55, 0x98, 0xec, 0x41, 0x4b, 0xa5, 0x17, 0x3c, 0xce, 0xe7, 0x92, 0x59, 0x35, 0xcd,
	0xb9, 0x05, 0xc8, 0x3b, 0x68, 0xb0, 0x9f, 0x22, 0x95, 0xd7, 0x56, 0xbd, 0x67, 0xf4, 0xdb, 0x6b,
	0x3d, 0xb8, 0xd1, 0x01, 0x4b, 0xae, 0xfd, 0x03, 0xcc, 0xdb, 0x45, 0x94, 0xc8, 0xb8, 0x62, 0x64,
	0x50, 0x9a, 0xaa, 0x97, 0x68, 0x0f, 0xad, 0x87, 0xcc, 0xc4, 0xd2, 0xfb, 0x03, 0xa8, 0x5e, 0x09,
	0xae, 0xd7, 0x6a, 0x0f, 0x5f, 0xac, 0x61, 0x2f, 0x27, 0x8c, 0xe6, 0xf9, 0x51, 0x9e, 0x61, 0xc1,
	0xb6, 0x7f, 0x57, 0xa0, 0xf3, 0x3f, 0x5e, 0x98, 0x27, 0x32, 0xb9, 0xb0, 0xa6, 0x8a, 0xfa, 0x5c,
	0xa8, 0xa3, 0x98, 0xbc, 0x62, 0xf2, 0x56, 0x9d, 0x85, 0x7c, 0xab, 0x30, 0x71, 0xc0, 0x8c, 0x55,
	0x21, 0x07, 0x4b, 0x0e, 0xb5, 0x70, 0x54, 0x68, 0x21, 0xdb, 0xc3, 0xed, 0x35, 0x9f, 0x44, 0x03,
	0xbc, 0x47, 0x27, 0x6f, 0xa1, 0xb9, 0xe8, 0x4a, 0x85, 0xd6, 0xf7, 0xc1, 0xd2, 0x1b, 0x1a, 0x79,
	0x0f, 0x70, 0x25, 0x38, 0x15, 0xfa, 0x3a, 0x96, 0xca, 0xef, 0xae, 0x2f, 0x2a, 0x18, 0x78, 0x87,
	0xfd, 0xea, 0x8f, 0x01, 0xad, 0x9b, 0x57, 0x41, 0x36, 0xa1, 0xe9, 0x8f, 0x22, 0x17, 0x71, 0x84,
	0xe6, 0x13, 0xf2, 0x1c, 0xb6, 0xa9, 0x3f, 0x76, 0xd1, 0x77, 0xbc, 0x28, 0x74, 0x71, 0xe2, 0x62,
	0x99, 0x32, 0xc8, 0x0e, 0x10, 0xea, 0x87, 0x63, 0xc7, 0x3f, 0x74, 0x23, 0x7f, 0x34, 0x8e, 0x8e,
	0x47, 0xa7, 0xfe, 0x91, 0x59, 0x21, 0x5d, 0x78, 0x1a, 0xe0, 0xe8, 0xec, 0x73, 0x44, 0xc3, 0xe8,
	0xf8, 0xd4, 0xf3, 0xcc, 0x2a, 0xd9, 0x86, 0x2e, 0xf5, 0x27, 0x8e, 0x47, 0x8f, 0xa2, 0x90, 0x7e,
	0xf0, 0x9d, 0xf1, 0x29, 0xba, 0x66, 0xad, 0x80, 0xdd, 0xb3, 0x80, 0xa2, 0x7b, 0x17, 0xae, 0x93,
	0x5d, 0xd8, 0x39, 0x71, 0xce, 0xa2, 0xc0, 0x41, 0xc7, 0xf3, 0x5c, 0x2f, 0x9a, 0x04, 0x7e, 0xe4,
	0xd1, 0x13, 0x3a, 0x36, 0x1b, 0xc3, 0xaf, 0xd0, 0xfd, 0xb2, 0xba, 0x14, 0x09, 0xa1, 0xb9, 0xb4,
	0x90, 0xd8, 0x8f, 0xf8, 0x5e, 0x3e, 0x91, 0xdd, 0x97, 0x8f, 0x72, 0x16, 0xb7, 0xef, 0xbc, 0xa1,
	0x7f, 0x36, 0x07, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x7b, 0x18, 0xff, 0x7e, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZeropsVpnProtocolClient is the client API for ZeropsVpnProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZeropsVpnProtocolClient interface {
	StartVpn(ctx context.Context, in *StartVpnRequest, opts ...grpc.CallOption) (*StartVpnResponse, error)
}

type zeropsVpnProtocolClient struct {
	cc *grpc.ClientConn
}

func NewZeropsVpnProtocolClient(cc *grpc.ClientConn) ZeropsVpnProtocolClient {
	return &zeropsVpnProtocolClient{cc}
}

func (c *zeropsVpnProtocolClient) StartVpn(ctx context.Context, in *StartVpnRequest, opts ...grpc.CallOption) (*StartVpnResponse, error) {
	out := new(StartVpnResponse)
	err := c.cc.Invoke(ctx, "/zeropsVpnProtocol.ZeropsVpnProtocol/startVpn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZeropsVpnProtocolServer is the server API for ZeropsVpnProtocol service.
type ZeropsVpnProtocolServer interface {
	StartVpn(context.Context, *StartVpnRequest) (*StartVpnResponse, error)
}

func RegisterZeropsVpnProtocolServer(s *grpc.Server, srv ZeropsVpnProtocolServer) {
	s.RegisterService(&_ZeropsVpnProtocol_serviceDesc, srv)
}

func _ZeropsVpnProtocol_StartVpn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVpnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZeropsVpnProtocolServer).StartVpn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zeropsVpnProtocol.ZeropsVpnProtocol/StartVpn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZeropsVpnProtocolServer).StartVpn(ctx, req.(*StartVpnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZeropsVpnProtocol_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zeropsVpnProtocol.ZeropsVpnProtocol",
	HandlerType: (*ZeropsVpnProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "startVpn",
			Handler:    _ZeropsVpnProtocol_StartVpn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}
