name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: test
        run: go test -v ./cmd/... ./src/...

  lint:
    name: lint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.0
          args: --verbose ./cmd/... ./src/...

  build:
    name: build ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      CGO_ENABLED: '0'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux amd64
            env:
              GOOS: linux
              GOARCH: amd64
          - name: linux 386
            env:
              GOOS: linux
              GOARCH: 386
          - name: darwin amd64
            env:
              GOOS: darwin
              GOARCH: amd64
          - name: darwin arm64
            env:
              GOOS: darwin
              GOARCH: arm64
          - name: windows amd64
            env:
              GOOS: windows
              GOARCH: amd64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: build
        env: ${{ matrix.env }}
        run: go build -v ./cmd/... ./src/...

  goreleaser-check:
    name: goreleaser check
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.5.0
          args: check
