name: release

on:
  release:
    types:
      - released
      - prereleased

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  goreleaser:
    name: build & upload artifacts
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: install upx
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.15.4
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: goreleaser
    if: github.event.action == 'released'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          cd tools/npm
          npm ci --ignore-scripts
          npm i -g replace-in-files-cli@2.2.0
          replace-in-files --string='v0.0.0-zerops' --replacement='${{ github.event.release.tag_name }}' package.json
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  report:
    needs: goreleaser
    if: github.event.action == 'released'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Notify discord about new release
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New version of `zcli` is ready!"
          nocontext: 'true'
          description: |
            Version `${{ github.event.release.tag_name }}`
            Changelog [here](${{ github.event.release.html_url }})
          color: 0xff91a4
          username: GitHub
